# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: david-why
email: david@loves-being-a.dev
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://davidwhy.me" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: dark
plugins:
  - jekyll-feed
  - jekyll-archives

include:
  - _pages

defaults:
  # all
  - scope:
      path: ""
    values:
      author: david-why
      layout: single
  # posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      permalink: /:categories/:title/
      breadcrumbs: true
      author_profile: true

jekyll-archives:
  enabled:
    - categories
  permalinks:
    category: '/:name/'
  layout: jekyll-archive

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
